apiVersion: v1
kind: Service
metadata:
  name: remodeling-service
spec:
  selector:
    app: remodelingApp
  type: NodePort
  ports: 
    - protocol: TCP
      port: 3701
      targetPort: 3700
      
